CrudPersonaMVC/Models/DBPersona.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPersonaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonaEntities2 : DbContext
    {
        public PersonaEntities2()
            : base("name=PersonaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Persona { get; set; }
    }
}

CrudPersonaMVC/Models/DBPersona.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\jroma\Desktop\Programacion Web\CRUD_MVC_.NET-master\CRUD_MVC_.NET-master\CrudPersonaMVC\Models\DBPersona.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

CrudPersonaMVC/Models/DBPersona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

CrudPersonaMVC/Models/Persona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPersonaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Edad { get; set; }
    }
}

CrudPersonaMVC/Models/ViewModels/ListarPersonas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CrudPersonaMVC.Models.ViewModels
{
    public class ListarPersonas
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int? Edad { get; set; }
    }
}

CrudPersonaMVC/Models/ViewModels/PersonaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrudPersonaMVC.Models.ViewModels
{
    public class PersonaViewModel
    {
        
        public int Id { get; set; }
        //indica que es requerido
        [Required]
        //nombre a mostrar 
        [Display (Name ="Nombre")]
        //valida el numero de caracteres igual a varchar(50) de nuestra bd
        [StringLength(50)]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        [StringLength(50)]
        public string Apellido { get; set; }
        [Required]
        public int? Edad { get; set; }
    }
}

CrudPersonaMVC/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrudPersonaMVC.Models;
using CrudPersonaMVC.Models.ViewModels;

namespace CrudPersonaMVC.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            //creamos una lista de nuestra clase ListarPersona
            List<ListarPersonas> list;            
            using (PersonaEntities2 bd = new PersonaEntities2())
            {
               //hacemos un select a nuestra tabla con los campos que queremos mostrar
                list = (from b in bd.Persona
                        select new ListarPersonas
                        {
                            Id = b.Id,
                            Nombre = b.Nombre,
                            Apellido = b.Apellido,
                            Edad = b.Edad,
                        }).ToList();
            }
                return View(list);
        }

        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(PersonaViewModel persona)
        {
            try
            {
                //validar datos
                if(ModelState.IsValid)
                {
                    //guardamos datos en bd
                  
                    using (PersonaEntities2 bd = new PersonaEntities2())
                    {
                        var opersona = new Persona();
                        opersona.Nombre = persona.Nombre;
                        opersona.Apellido = persona.Apellido;
                        opersona.Edad = persona.Edad;

                        bd.Persona.Add(opersona);
                        bd.SaveChanges();
                    }
                    //luego de agregar registro redirecionamos hacia nuestro index
                    return Redirect("~/Persona/");
                }

                return View(persona);
            }

            catch(Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            PersonaViewModel model = new PersonaViewModel();
            using (PersonaEntities2 bd = new PersonaEntities2())
            {
                var opersona = bd.Persona.Find(id);//obtenemos registro por medio de id
                model.Id = opersona.Id;
                model.Nombre = opersona.Nombre;
                model.Apellido = opersona.Apellido;
                model.Edad = opersona.Edad;
            }

            return View(model);

        }
        [HttpPost]
        public ActionResult Editar(PersonaViewModel persona)
        {
            try
            {
                //validar datos
                if (ModelState.IsValid)
                {
                    //guardamos datos en bd
                    using (PersonaEntities2 bd = new PersonaEntities2())
                    {
                        var opersona = bd.Persona.Find(persona.Id);//obtenemos registro por medio de id
                        opersona.Nombre = persona.Nombre;
                        opersona.Apellido = persona.Apellido;
                        opersona.Edad = persona.Edad;

                        //editamos registro
                        bd.Entry(opersona).State = System.Data.Entity.EntityState.Modified;
                        bd.SaveChanges();
                    }

                    return Redirect("~/Persona/");
                }

                return View(persona);
            }

            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        [HttpPost]
        public ActionResult Eliminar(int id)
        {

            PersonaViewModel model = new PersonaViewModel();
            using (PersonaEntities2 bd = new PersonaEntities2())
            {
                var opersona = bd.Persona.Find(id);//obtengo entidad con id

                bd.Persona.Remove(opersona);

                bd.SaveChanges();

            }
            return Content("ok");
        }

    }
}

CrudPersonaMVC/Views/Persona/Editar.cshtml
@model CrudPersonaMVC.Models.ViewModels.PersonaViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Persona", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(p => p.Id);
            <div class="form-group">
                @Html.LabelFor(p => p.Nombre):
                @Html.TextBoxFor(p => p.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Nombre, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Apellido):
                @Html.TextBoxFor(p => p.Apellido, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Apellido, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Edad):
                @Html.TextBoxFor(p => p.Edad, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Edad, null, new { @class = "text-danger" })
            </div>
            <br />
            <div style="text-align:center">
                <input type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        </div>
    </div>
}

CrudPersonaMVC/Views/Persona/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<center><h2>Datos Personas</h2></center>
<!-- Boton Nuevo  -->
<div class=" row" style="text-align:right; padding:5px">
    <div class="col-md-12">
        <input type="button" class="btn btn-primary" value="Nuevo" onclick="document.location.href='@Url.Content("~/Persona/Nuevo")'" />
    </div>
</div>
<!-- Creo tabla  -->
<div class="row">
    <div class="col-md-12">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>NOMBRE</th>
                    <th>APELLIDO</th>
                    <th>EDAD</th>
                    <th>Editar/Eliminar</th>
                </tr>
            </thead>
            <!-- Recorro el modelo para imprimir datos -->
            @foreach (var elemento in Model)
            {
                <tr>
                    <td>@elemento.Id</td>
                    <td>@elemento.Nombre</td>
                    <td>@elemento.Apellido</td>
                    <td>@elemento.Edad</td>

                    <td>
                        <!-- Botones Editar Eliminar  -->
                        <input type="button" onclick="document.location.href='@Url.Content("~/Persona/Editar/"+elemento.Id)'" value="Editar" class="btn btn-default" />
                        <input type="button" onclick="jsEliminar(@elemento.Id);" class="btn btn-danger" value="Eliminar" />
                    </td>
                </tr>
            }
        </table>
    </div>
</div>







<script>
    function jsEliminar(id) {
        if (confirm("Quieres Eliminar El Registro?")) {
            url = "@Url.Content("~/Persona/Eliminar")" + "/"+id; //metodo Eliminar Controller

            $.post(url, function (data) {
                
                if (data=="ok") {
                    document.location.href = "@Url.Content("~/Persona/")"
                    console.log("Exito");
                } else {
                    alert("No se pudo Eliminar El registro");
                }

            })
        }
    }
</script>

CrudPersonaMVC/Views/Persona/Nuevo.cshtml
@model CrudPersonaMVC.Models.ViewModels.PersonaViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo</h2>

@using (Html.BeginForm("Nuevo","Persona", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <!-- Creo label   -->
                @Html.LabelFor(p => p.Nombre):
                <!-- Creo textbox  -->
                @Html.TextBoxFor(p => p.Nombre, "", new { @class = "form-control" })
                <!-- para mostrar mensaje de error  -->
                @Html.ValidationMessageFor(p => p.Nombre, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Apellido):
                @Html.TextBoxFor(p => p.Apellido, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Apellido, null, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Edad):
                @Html.TextBoxFor(p => p.Edad, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(p => p.Edad, null, new { @class = "text-danger" })
            </div>
            <br/>
            <div style="text-align:center">
                <input  type="submit" class="btn btn-primary" value="Guardar" />
            </div>
        </div>
    </div>
}

CrudPersonaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UNIVERSIDA MARIANO GALVEZ </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">CRUD MVC5 </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#about">Acerca de</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#services">Servicios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#contact">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <header class="bg-primary text-white">
            <div class="container text-center">
                <h1>CRUD MVC</h1>
                <p class="lead">ING. JOSE VINICIO PEÑA</p>
            </div>
        </header>
        @RenderBody()
        <hr />
        <section id="contact">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <center>
                            <h3>Visita mi Blog</h3>
                            <p class="lead"><a href="http://cristiantorresalfaro.blogspot.com/" target="_blank">Mi Blog</a></p>
                        </center>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <footer>
            <center><p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p></center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>